# File Imput and Output with Arrays

In [1]:
import numpy as np
import pandas as pd

NumPy es capaz de guardar y cargar datos hacia y desde disco en formato texto o binario. En otros capitulos se aprendera sobre herramientas de Pandas para la lectura de datos tabulares en memoria

## Storing Arrays on Disk in Binary Format 

np.save y np.load son las dos funciones para en forma eficiente guardar y cargar datos de arrays en disco. Arrays son guardados por default en formato binario con extension de archivo .npy

In [2]:
arr = np.arange(10) #Creo un array

In [4]:
arr #Visualizo el array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.save("some_array",arr) #Guardo el array en disco con el nombre "some_array"

Si el nombre del archivo no termina con la extencion .npy entonces la misma sera incluida.

El array en disco puede ser cargado utilizando np.load:

In [7]:
np.load("some_array.npy") #Cargo el array que se encuentra en disco

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Se pueden guardar varios arrays en un archivo zip utilizando np.savez y pasando los arrays como argumentos tipo palabras claves:

In [8]:
np.savez("array_archive.npz",a=arr,b=arr) #Guardo los array en un archivo zip

Cuando se carga un archivo .npz se debe especificar el array que se desea cargar:

In [9]:
arch = np.load("array_archive.npz")

In [11]:
arch["b"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])